version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    ports:
      - "4567:4567"
    env_file:
      - .env
      - .env-dev-values
        
volumes:
  gem_cache:
